# Generated by Django 5.1.4 on 2025-01-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='cylinders',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='dealer_id',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='engine_capacity',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='horsepower',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='torque',
        ),
    ]
